#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso phaseModel
wclean libso interfacialModels
wclean libso kineticTheoryModels
wclean libso derivedFvPatchFields
wclean

# ----------------------------------------------------------------- end-of-file
